---
- hosts: "atom"
  gather_facts: False # Required to bootstrap python install

  pre_tasks:
    # Bootstrap python on target node (required for ansible to work)
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - setup: # Turn gather_facts back on

    - include_vars: "vars-singlenode.yml"
      tags:
        - "always"

  roles:

    - role: "ufw"
      become: "yes"
      tags:
        - "ufw"

    - role: "elasticsearch"
      become: "yes"
      tags:
        - "elasticsearch"

    - role: "percona"
      become: "yes"
      tags:
        - "percona"

    - role: "memcached"
      become: "yes"
      tags:
        - "memcached"

    - role: "gearman"
      become: "yes"
      tags:
        - "gearman"

    - role: "nginx"
      become: "yes"
      tags:
        - "nginx"

    - role: "atom"
      become: "yes"
      tags:
        - "atom"
