---
- hosts: "atom"
  gather_facts: no

  pre_tasks:

    # Bootstrap python on target node (required for ansible to work)
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - include_vars: "vars-singlenode.yml"
      tags:
        - "always"

    - setup: # Now gather_facts
      tags:
        - "always"

  roles:

    - role: "ufw"
      become: "yes"
      tags:
        - "ufw"

    - role: "artefactual.elasticsearch"
      become: "yes"
      tags:
        - "elasticsearch"

    - role: "artefactual.percona"
      become: "yes"
      tags:
        - "percona"

    - role: "artefactual.memcached"
      become: "yes"
      tags:
        - "memcached"

    - role: "artefactual.gearman"
      become: "yes"
      tags:
        - "gearman"

    - role: "artefactual.nginx"
      become: "yes"
      tags:
        - "nginx"

    - role: "artefactual.atom"
      become: "yes"
      tags:
        - "atom"
      notify:
        - Clear sf_cache
        - Reload nginx
        - Restart php-fpm
