# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  {
    "am-pkg-local" => { 
    "ip" => "192.168.168.194',
    "memory" => "2048",
    "cpus" => "2",
    },
  }.each do |short_name, properties|

    # Define guest
    config.vm.define short_name do |host|
      host.vm.network "private_network", ip: properties.fetch("ip")
    end

    # Set the amount of RAM and virtual CPUs for the virtual machine
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", properties.fetch("memory")]
      vb.customize ["modifyvm", :id, "--cpus", properties.fetch("cpus")]
    end

  end

  # Ansible provisioning
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "./singlenode.yml"
    ansible.host_key_checking = false
    # accept multiple arguments, separated by colons
    ansible.raw_arguments = ENV['ANSIBLE_ARGS'].to_s.split(':')
  end
end